### ISSUE TITLE
Different rendering with <p> tag

### ISSUE THREAD

**Issue by marienfressinaud** [diaspora/diaspora#5626]
An easy one. I found a small rendering problem with `<p>` tag. If you have a look at my screenshot, you'll see on the first post there is no space between paragraph and list (this is the problem). In the second post, we can see a little margin (that's ok).

![capture d ecran de 2015-02-06 17 19 05](https://cloud.githubusercontent.com/assets/1436309/6082881/c11c1e5a-ae24-11e4-8b48-ad429a0b91f4.png)

Problem comes from the following CSS properties:

```css
.stream_element .collapsible p {
    margin: 0px 0px 0.8em;
}
.stream_element .collapsible p:last-of-type {
    margin: 0px;
}
```

A better way to handle that would be to always have margin at the top and the bottom of both `<p>` and `<ul>` tags.
