### ISSUE TITLE
The captcha_length in diaspora.yml is being ignored

### ISSUE THREAD

**Issue by RichKavanagh** [diaspora/diaspora#5932]
The value applied to *captcha_length* in diaspora.yml is being completely ignored.

Check the signup page on any v0500 pod, the are all only showing 1 captcha character.

I'm going to disable signups on my pod for now.

**Comment by jhass** [comment]
Shit, indeed.

You can workaround with:

```yml
default:
  settings:
    captcha_length: 5
```

That is defining the key `settings.captcha_length`.
