### ISSUE TITLE
XMPP and Nginx reverse proxy

### ISSUE THREAD

**Issue by nazar-pc** [diaspora/diaspora#6298]
Didn't found any good explanation about how to setup it properly.
Initially I've installed Diaspora with this Docker image: https://github.com/Chocobozzz/Diaspora-Docker
Currently I'm on 0.5.2 stable.
Chat section added to `diaspora.yml`, but it doesn't work at all and I'm getting warning about BOSH:
```yml
  chat: ## Section
    
    ## Enable the chat service and all its components.
    enabled: true
    
    ## Custom XMPP server configuration goes here.
    server: ## Section
    
      ## Start built-in XMPP server (default=true).
      ## In case you want to run your own server, you should disable it.
      #enabled: false
    
      ## Set the directory in which to look for virtual hosts'
      ## TLS certificates.
      #certs: 'config/vines'
    
      ## The server accepts by default only valid certificates.
      ## Any connection which uses self-signed ones will be closed.
      ## If you'd like to accept self-signed certificates
      ## on your server, set the next option to true.
      #accept_self_signed: true
    
      ## Only edit the next option if you'd like to deny
      ## your users to exchange messages between other XMPP servers.
      #cross_domain_messages: false
      
      ## Set the maximum of offline messages stored per user (default=150).
      ## If it exceeds, it will start deleting old messages. You can disable
      ## offline message support completely by setting the option to zero.
      #max_offline_msgs: 150

      ## Client to server
      c2s: ## Section
      
        ## Configure the address that vines should listen on.
        #address: '0.0.0.0'

        ## Configure the client-to-server port.
        #port: 5222
      
        ## The maximum we'd like to allow for stanza size.
        #max_stanza_size: 65536
      
        ## The max_resources_per_account attribute, limits how many
        ## concurrent connections one user can have to the server.
        #max_resources_per_account: 5
      
      ## Server to server
      s2s: ## Section
    
        ## Configure the address that vines should listen on.
        #address: '0.0.0.0'
      
        ## Configure the server-to-server port.
        #port: 5269
      
        ## The max_stanza_size attribute should be
        ## much larger than the setting for client-to-server.
        #max_stanza_size: 131072
      
        ## By default every XMPP server with a valid certificate
        ## is able to communicate with your server. In case of a
        ## malicious server (e.g. spam reason), you can black-list them.
        #blacklist:
        #  - 'example.com'
        #  - 'malicous.net'
    
      ## XEP-0124 BOSH requests
      bosh: ## Section
    
        ## If you'd like to use a proxy, you should set the proxy
        ## option to true, otherwise jsxc always tries to
        ## connect directly to the port specified below.
        #proxy: true
      
        ## Configure the address that vines should listen on.
        #address: '0.0.0.0'
      
        ## Configure the BOSH port.
        #port: 5280
      
        ## Configure the bind endpoint.
        #bind: '/http-bind'
    
        ## The maximum we'd like to allow for stanza size.
        #max_stanza_size: 65536
  
        ## The max_resources_per_account attribute, limits how many
        ## concurrent connections one user can have to the server.
        #max_resources_per_account: 5

      ## Specify log behaviour here.
      log: ## Section

        ## Log file location.
        #file: 'log/vines.log'
    
        ## Set the logging level to debug, info, warn, error, or fatal.
        ## The debug level logs all XML sent and received by the server.
        #level: 'info'
```
Certificates placed in `config/vines` as it should be.

But here is the trick. My server is behind CloudFlare, there is Nginx on host as reverse-proxy with config:
```
server {
    listen      80;
    server_name diaspora.mokrynskyi.com;
    return      301 https://$server_name$request_uri;
}
server {
	listen						443 ssl spdy;
	server_name					diaspora.mokrynskyi.com;
	ssl_certificate				/etc/ssl/diaspora.mokrynskyi.com.ssl.crt;
	ssl_certificate_key			/etc/ssl/diaspora.mokrynskyi.com.ssl.key;
	keepalive_timeout			70;
	client_max_body_size		100m;
	location / {
		proxy_pass			https://127.0.0.1:{some_port};
		proxy_set_header	Host					$host;
		proxy_set_header	X-Real-IP				$remote_addr;
        proxy_set_header	X-Forwarded-Proto		https;
	}
}

```

And here is config from Nginx in Docker container:
```
server {
    listen 80;

    server_name diaspora.mokrynskyi.com;
    rewrite ^/(.*) https://diaspora.mokrynskyi.com/$1 permanent;
}

server {
    listen 443 ssl spdy;
    server_name diaspora.mokrynskyi.com;
    root /home/diaspora/diaspora/public;

    # Configure maximum picture size
    # Note that Diaspora has a client side check set at 4M
    client_max_body_size 100M;

    ssl_certificate /home/diaspora/diaspora.crt;
    ssl_certificate_key /home/diaspora/diaspora.key;

    ssl_ciphers RC4:HIGH:!aNULL:!MD5;
    ssl_session_timeout 5m;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;

    # Proxy if requested file not found
    try_files $uri @diaspora;

    location @diaspora {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $http_host;
        proxy_redirect off;

        proxy_pass http://diaspora_server;
    }
}

upstream diaspora_server {
    server 127.0.0.1:3000;
}
```

I guess these configs need some adjustments to make XMPP working? I have empty list of users all the time.
