### ISSUE TITLE
After unignoring an user a flash-message asks me to sayhello

### ISSUE THREAD

**Issue by DeusFigendi** [diaspora/diaspora#6900]
Just a little… I just removed some users from my ignorelist and I've been a little confused about the success-message that appears in a flash-message (you know that stuff that comes in from the top) and it's saying:

> Mal sehen was sie zu sagen haben! #sayhello

I'd guess that's not what it should be.

I did this on geraspora so the version is 0.5.99.0-pd1e959a2

oh and btw. the result of removing an ignorition is "302 found"

**Comment by denschub** [comment]
Ehm? The message you quoted is `blocks.destroy.success` and gets added in [app/controllers/blocks_controller.rb, L24](https://github.com/diaspora/diaspora/blob/develop/app/controllers/blocks_controller.rb#L24). It does exactly what it's supposed to do. If you feel like we should change the message, that's probably something to discuss on WTI.

Closing, this is not an issue...

**Comment by svbergerem** [comment]
The English texts are:
```
  blocks:
    create:
      success: "All right, you won’t see that user in your stream again. #silencio!"
      failure: "I couldn’t ignore that user.  #evasion"
    destroy:
      success: "Let’s see what they have to say! #sayhello"
      failure: "I couldn’t stop ignoring that user.  #evasion"
```

If anyone thinks that these should change and they have a better idea then please open a PR with that change or a new issue.
